# The minimal profile will install just the core control plane
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: 1-13-9
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
