---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway-canary
spec:
  selector:
    matchLabels:
      istio: ingressgateway
      app: istio-ingressgateway-canary
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        istio: ingressgateway
        app: istio-ingressgateway-canary
        istio.io/rev: canary
    spec:
      containers:
      - name: istio-proxy
        image: auto
---
